dataset_1:
    freq: 15T
    seasonality: 96 # daily 96 = 24 * (60/15)
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
        method: arima
        feature_method: seasonal_diff
        n_splits: 1
        num_predictions: 192
        model_configs:
            order: [3, 0, 1]
dataset_2:
    freq: 5T
    seasonality: 288 # daily 288 = 24 * (60/5)
    visualize_freq: D
    anomalies:
      method: rolling_std
      window_size: 12
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 576
      model_configs:
        order: [2, 0, 1]
dataset_3:
    freq: 5T
    seasonality: 288 # daily 288 = 24 * (60/5)
    visualize_freq: D
    anomalies:
      method: rolling_mean
      window_size: 12
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 576
      model_configs:
        order: [3, 0, 1]
dataset_4:
    freq: 5T
    seasonality: 2016 # weekly 2016 = 24 * 7 * (60/5)
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 576
      model_configs:
        order: [1, 0, 1]
dataset_5:
    freq: 5T
    seasonality: 204 #  204 = 17 * (60/5)
    visualize_freq: D
    anomalies:
      method: rolling_std
      window_size: 12
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 72
      model_configs:
        order: [1, 0, 1]
dataset_6:
    freq: 5T
    seasonality: 204 #  204 = 17 * (60/5)
    visualize_freq: D
    anomalies:
      method: rolling_std
      window_size: 12
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 72
      model_configs:
        order: [2, 0, 1]
dataset_7:
    freq: 5T
    seasonality: 288 # daily 288 = 24 * (60/5)
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 72
      model_configs:
        order: [2, 0, 2]
dataset_8:
    freq: 1H
    seasonality: 24 # daily 24 = 24 * 1
    visualize_freq: m
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 24
      model_configs:
        order: [2, 0, 2]
dataset_9:
    freq: 5T
    seasonality: 288 # daily 288 = 24 * (60/5)
    visualize_freq: D
    anomalies:
      method: rolling_std
      window_size: 12
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 72
      model_configs:
        order: [2, 0, 1]
dataset_10:
    freq: 5T
    seasonality: 288 # daily 288 = 24 * (60/5)
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 72
      model_configs:
        order: [4, 0, 1]
dataset_11:
    freq: 5T
    seasonality: 100 # daily 100 = 6 * (60/5)
    visualize_freq: D
    anomalies:
      method: rolling_std
      window_size: 12
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 72
      model_configs:
        order: [3, 0, 3]
dataset_12:
    freq: 5T
    seasonality: 288 # daily 288 = 24 * (60/5)
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 72
      model_configs:
        order: [1, 0, 1]
dataset_13:
    freq: 1T
    seasonality: 1440 # daily 1440 = 24 * 60
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 5
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 72
      model_configs:
        order: [2, 0, 1]
dataset_100:
    freq: 1T
    seasonality: 1440 # daily 1440 = 24 * 60
    visualize_freq: D
    anomalies: 
      method: rolling_mean
      window_size: 60
      threshold: 5
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 360
      model_configs:
        order: [1, 0, 1]
dataset_101:
    freq: 1T
    seasonality: 1440 #10080 #weekly: 10080 = 24 * 7 * 60
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 5
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 360
      model_configs:
        order: [1, 0, 1]
dataset_102:
    freq: 1T
    seasonality: 1440 # daily 1440 = 24 * 60
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 360
      model_configs:
        order: [2, 0, 1]
dataset_103:
    freq: 1T
    seasonality: 1440 #8640 # every 6 days: 8640 = 24 * 360
    visualize_freq: D
    anomalies: 
      method: rolling_mean
      window_size: 60
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 360
      model_configs:
        order: [1, 0, 1]
dataset_105:
    freq: 1T
    seasonality: 720 # halfdaily 1440 = 24 * 60
    visualize_freq: D
    anomalies: 
      method: rolling_std
      window_size: 60
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 360
      model_configs:
        order: [1, 0, 1]
dataset_106:
    freq: 30T
    seasonality: 48 # daily 48 = 24 * 2
    visualize_freq: D
    anomalies: 
      method: rolling_std
      window_size: 60
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 96
      model_configs:
        order: [1, 0, 1]
dataset_201:
    freq: 5T
    seasonality: 288 # daily 2016 = 24 * 7 * (60/5)
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 360
      model_configs:
        order: [1, 0, 1]
dataset_202:
    freq: 5T
    seasonality: 12 # hourly: 60/5
    visualize_freq: D
    anomalies: 
      method: rolling_mean
      window_size: 24
      threshold: 5
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 60
      model_configs:
        order: [1, 0, 1]
dataset_203:
    freq: 5T
    seasonality: 288 # daily
    visualize_freq: D
    anomalies: 
      method: rolling_std
      window_size: 12
      threshold: 5
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 360
      model_configs:
        order: [1, 0, 1]
dataset_204:
    freq: 5T
    seasonality: 288 # daily 2016 = 24 * 7 * (60/5)
    visualize_freq: D
    anomalies: 
      method: rolling_mean
      window_size: 24
      threshold: 5
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 60
      model_configs:
        order: [1, 0, 1]
dataset_205:
    freq: 5T
    seasonality: 12 # daily 2016 = 24 * 7 * (60/5)
    visualize_freq: D
    anomalies: 
      method: rolling_mean
      window_size: 12
      threshold: 5
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 60
      model_configs:
        order: [2, 0, 1]
dataset_206:
    freq: 1T
    seasonality: 1440 # daily 1440 = 24 * 60
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 5
    forecast:
      method: arima
      feature_method: seasonal_diff
      n_splits: 1
      num_predictions: 360
      model_configs:
        order: [2, 0, 1]



# method: prophet
# feature_method: norm
# n_splits: 1
# num_predictions: 48
# model_configs: {}
