tuner:
    n_trials: 15
    direction: minimize
    n_splits: 3 #cross validation
    # use_best_params: True
dataset_1: #ok
    freq: 15T
    seasonality: 96 # daily 96 = 24 * (60/15)
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      num_predictions: 96
      fe_method: seasonal_diff
dataset_2: #ok
    freq: 5T
    seasonality: 60 # daily 288 = 24 * (60/5)
    visualize_freq: D
    anomalies:
      method: rolling_std
      window_size: 12
      threshold: 3
    forecast:
      method: arima
      num_predictions: 288
      fe_method: seasonal_diff
dataset_3: #ok
    freq: 5T
    seasonality: 60 # daily 288 = 24 * (60/5)
    visualize_freq: D
    anomalies:
      method: rolling_mean
      window_size: 12
      threshold: 3
    forecast:
      method: arima
      num_predictions: 288
      fe_method: seasonal_diff
dataset_4: #ok
    freq: 5T
    seasonality: 2016 # weekly 2016 = 24 * 7 * (60/5)
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      num_predictions: 288
      fe_method: seasonal_diff
dataset_5:
    freq: 5T
    seasonality: 288 #  204 = 17 * (60/5)
    visualize_freq: D
    anomalies:
      method: stl
      threshold: 3
    forecast:
      method: arima
      num_predictions: 60
      fe_method: norm
dataset_6: #ok
    freq: 5T
    seasonality: 204 #  204 = 17 * (60/5)
    visualize_freq: D
    anomalies:
      method: rolling_std
      window_size: 12
      threshold: 3
    forecast:
      method: arima
      num_predictions: 288
      fe_method: seasonal_diff
dataset_7:
    freq: 5T
    seasonality: 2 # daily 288 = 24 * (60/5)
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      num_predictions: 288
      fe_method: seasonal_diff
dataset_8:
    freq: 1H
    seasonality: 24 # daily 24 = 24 * 1
    visualize_freq: m
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      num_predictions: 24
dataset_9: #ok
    freq: 5T
    seasonality: 12 # daily 288 = 24 * (60/5)
    visualize_freq: D
    anomalies:
      method: rolling_std
      window_size: 12
      threshold: 3
    forecast:
      method: arima
      num_predictions: 288
      fe_method: seasonal_diff
dataset_10: #ok
    freq: 5T
    seasonality: 288 # daily 288 = 24 * (60/5)
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      num_predictions: 288
dataset_11: #ok
    freq: 5T
    seasonality: 100 # daily 100 = 6 * (60/5)
    visualize_freq: D
    anomalies:
      method: stl
      threshold: 3
    forecast:
      method: arima
      num_predictions: 100
      fe_method: seasonal_diff
dataset_12: #ok
    freq: 5T
    seasonality: 288 # daily 288 = 24 * (60/5)
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      num_predictions: 288
      fe_method: seasonal_diff
dataset_13:
    freq: 1T
    seasonality: 1440 # daily 1440 = 24 * 60
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 5
    forecast:
      method: arima
      num_predictions: 1440
      fe_method: seasonal_diff
dataset_100:
    freq: 1T
    seasonality: 60 # daily 1440 = 24 * 60
    visualize_freq: D
    anomalies: 
      method: rolling_mean
      window_size: 60
      threshold: 5
    forecast:
      method: arima
      num_predictions: 1440
      fe_method: seasonal_diff
dataset_101:
    freq: 1T
    seasonality: 1440 #10080 #weekly: 10080 = 24 * 7 * 60
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 5
    forecast:
      method: arima
      num_predictions: 1440
      fe_method: seasonal_diff
dataset_102:
    freq: 1T
    seasonality: 1440 # daily 1440 = 24 * 60
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      num_predictions: 1440
      fe_method: seasonal_diff
dataset_103:
    freq: 1T
    seasonality: 1440 #8640 # every 6 days: 8640 = 24 * 360
    visualize_freq: D
    anomalies: 
      method: rolling_mean
      window_size: 60
      threshold: 3
    forecast:
      method: arima
      num_predictions: 1440
dataset_105:
    freq: 1T
    seasonality: 720 # halfdaily 1440 = 24 * 60
    visualize_freq: D
    anomalies: 
      method: rolling_std
      window_size: 60
      threshold: 3
    forecast:
      method: arima
      num_predictions: 1440
      fe_method: seasonal_diff
dataset_106:
    freq: 30T
    seasonality: 48 # daily 48 = 24 * 2
    visualize_freq: D
    anomalies: 
      method: rolling_std
      window_size: 60
      threshold: 3
    forecast:
      method: arima
      num_predictions: 48
dataset_201:
    freq: 5T
    seasonality: 288 # daily 2016 = 24 * 7 * (60/5)
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      num_predictions: 288
      fe_method: seasonal_diff
dataset_202:
    freq: 5T
    seasonality: 12 # hourly: 60/5
    visualize_freq: D
    anomalies: 
      method: rolling_mean
      window_size: 24
      threshold: 5
    forecast:
      method: arima
      num_predictions: 288
      fe_method: seasonal_diff
dataset_203:
    freq: 5T
    seasonality: 288 # daily
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 3
    forecast:
      method: arima
      num_predictions: 288
      fe_method: seasonal_diff
dataset_204:
    freq: 5T
    seasonality: 24 # daily 2016 = 24 * 7 * (60/5)
    visualize_freq: D
    anomalies: 
      method: rolling_mean
      window_size: 24
      threshold: 5
    forecast:
      method: arima
      num_predictions: 288
      fe_method: seasonal_diff
dataset_205:
    freq: 5T
    seasonality: 2016 # weekly 2016 = 24 * 7 * (60/5)
    visualize_freq: D
    anomalies: 
      method: rolling_mean
      window_size: 12
      threshold: 5
    forecast:
      method: arima
      num_predictions: 2016
      fe_method: seasonal_diff
dataset_206:
    freq: 1T
    seasonality: 1440 # daily 1440 = 24 * 60
    visualize_freq: D
    anomalies: 
      method: stl
      threshold: 5
    forecast:
      method: arima
      num_predictions: 1440
      fe_method: seasonal_diff